---
- name: check for ssh
  hosts: app, graylog
  gather_facts: no
  tasks:
    - name: check ssh state
      wait_for:
        port: 22
        host: '{{ ansible_host }}'
        search_regex: OpenSSH
        delay: 5
      connection: local

- name: system preparations
  hosts: graylog, app
  become: yes
  tasks:
    - name: apt update
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: edit hostfiles
      lineinfile:
        path: /etc/hosts
        line: "{{ hostvars[item]['ansible_facts']['eth1']['ipv4']['address'] }} {{ hostvars[item]['ansible_hostname'] + '.internal' }}"
      with_items: "{{ groups['graylog'] + groups['app'] }}"
    - name: download install fluentd
      get_url:
        url: https://toolbelt.treasuredata.com/sh/install-ubuntu-focal-td-agent4.sh
        dest: .
        mode: '0555'
    - name: run install script
      command: sh ./install-ubuntu-focal-td-agent4.sh

- name: install java
  hosts: graylog
  become: yes
  pre_tasks:
    - name: Update apt
      become: yes
      apt:
        cache_valid_time: 3600
        update_cache: yes
  roles:
    - gantsign.java
  tasks:
    - name: find java
      command: find /opt/java -type f -name java
      register: this
    - name: link java bin
      file:
        src: '{{ this.stdout }}'
        dest: /usr/bin/java
        state: link
#    - name: copy fluentd config
#      copy:
#        src: files/td-agent.log.conf
#        dest: /etc/td-agent/td-agent.conf
#    - name: restart fluentd
#      service:
#        name: td-agent
#        state: restarted

- name: install es
  hosts: graylog
  become: yes
  roles:
    - elastic.elasticsearch
  vars:
    es_heap_size: 1g
    es_config:
      node.name: '{{ ansible_hostname | quote }}'
      http.host: '{{ "localhost," + ansible_facts["eth1"]["ipv4"]["address"] }}'
      http.port: 9200  

- name: install graylog
  hosts: graylog
  become: true
  vars:
    graylog_version: 4.1
    graylog_install_java: False # Elasticsearch role already installed Java
    graylog_install_elasticsearch: False
    graylog_password_secret: "2jueVqZpwLLjaWxV" # generate with: pwgen -s 96 1
    graylog_root_password_sha2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
    graylog_http_bind_address: "{{ ansible_default_ipv4.address }}:9000"
    graylog_http_publish_uri: "http://{{ ansible_default_ipv4.address }}:9000/"
    graylog_http_external_uri: "http://{{ ansible_default_ipv4.address }}:9000/"
  roles:
    - graylog2.graylog-ansible-role

- name: install nginx, configure rsyslog
  hosts: app
  become: yes
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: latest
    - name: copy rsyslog config
      copy:
        src: files/rebrain.conf
        dest: /etc/rsyslog.d/
    - name: rsyslog restart
      service:
        name: rsyslog
        state: restarted
