---
molecule:
  # directory in CWD to place all temp files, etc.
  molecule_dir: .molecule

  # where temporary state will be stored (lives under molecule_dir)
  state_file: state

  goss_dir: tests/goss
  goss_playbook: verifier.yml

  # directories to ignore when doing trailing whitespace checks on files during verify command
  ignore_paths:
    - .git
    - .vagrant
    - .molecule
  # directory containing group_vars to use with ansible
  group_vars: tests/group_vars

verifier:
  name: goss

# ansible related configuration
ansible:
  playbook: tests/playbook.yml

dependency:
  name: galaxy

driver:
  name: docker

docker:
  containers:
    - name: fluentd.cont
      ansible_groups:
        - fluentd
      image: geerlingguy/docker-debian9-ansible
      image_version: latest

      privileged: True
      cap_add:
        - SYS_ADMIN
      volume_mounts:
        - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      command: '/lib/systemd/systemd'

# configuration options for the internal call to vagrant
vagrant:
  # molecule's --platform option will look for these names
  raw_config_args:
    - "landrush.enabled = true"
    - "landrush.tld = 'vm'"
    - "landrush.guest_redirect_dns = false"
    - "vm.network 'forwarded_port', guest: 8080, host: 9999"
  platforms:
    - name: Debian9
      box: debian/stretch64

  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 256
        cpus: 1

  instances:
    - name: fluentd.vm
      ansible_groups:
        - fluentd
      interfaces:
        - network_name: private_network
          type: dhcp
          auto_config: true
