---
- name: check for ssh
  hosts: all
  become: yes
  gather_facts: no
  vars:
    token: 2c6485d0-1344-49f1-9faf-db7fee582d66
  tasks:
#    - name: check ssh state
#      wait_for:
#        port: 22
#        host: '{{ ansible_host }}'
#        search_regex: OpenSSH
#        delay: 5
#      connection: local
    - name: apt update
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: download install script
      get_url:
        url: https://toolbelt.treasuredata.com/sh/install-ubuntu-focal-td-agent4.sh
        dest: .
        mode: '0555'
    - name: run install script
      command: sh ./install-ubuntu-focal-td-agent4.sh
    - name: install loggly plugin
      command: /opt/td-agent/bin/fluent-gem install fluent-plugin-loggly
    - name: copy fluentd config
      template:
        src: files/td-agent.log.conf.j2
        dest: /etc/td-agent/td-agent.conf
        mode: '0644'
    - name: restart fluentd
      service:
        name: td-agent
        state: restarted
